name: "Terraform Pipeline Provision EC2"

on:
  push:
    branches: ['master', 'main']

permissions:
    contents: write

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_CLOUD_ORGANIZATION: "GiorgioDev"
  TF_WORKSPACE: "simple-api"
  TF_API_TOKEN: ${{secrets.TF_API_TOKEN}}
  CONFIG_DIRECTORY: "./deployments/terraform/terraform-aws-ec2-tf/terraform"


jobs:
  terraform:
    name: "Terraform Pipeline Provision EC2 with TF Cloud"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./deployments/terraform/terraform-aws-ec2-tf/terraform

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Terraform init
        id: init
        run: terraform init -lock=false
        env:
          TF_API_TOKEN: ${{secrets.TF_API_TOKEN}}

      - name: Terraform format
        id: fmt
        run: terraform fmt

      - name: Terraform validate
        id: validate
        run: terraform validate
        env:
          GITHUB_TOKEN: ${{secrets.G_TOKEN}}
          TFE_TOKEN: ${{secrets.TF_API_TOKEN}}

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false -lock=false