pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhubcredentials')
        appName = "server"
        registry = ""
        registryCredential = ""
        projectPath = ""
        // AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
        // AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
        // AWS_REGION = 'aws_region'
        // EC2_INSTANCE = 'ec2_instance_id'
        SSH_KEY = credentials('ssh_key')
    }
    stages {
        stage('Environment'){
        steps {
            // sh 'node --version'
                git branch: 'main', url: 'https://github.com/gventuraagramonte/simple-api.git'
                sh 'echo repositorio clonado'
                }
        }
        
        stage('Build'){
            steps {
                sh 'docker build -t giorgio0603/simple-api:latest --no-cache .'
                sh 'echo imagen compilada'
            }
        }
        
        // stage('Login'){
        //     steps {
        //         sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
        //     }
        // }

        // stage('Docker Push') {
        //     steps {
        //         sh 'docker images'
        //         sh 'docker push giorgio0603/simple-api:latest'
        //     }
        // }
    }
}